version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:80"

  backend:
    build:
      context: ./backend
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/market
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # 挂载初始化脚本

  redis:
    image: redis:7.0
    ports:
      - "6379:6379"
