server:
    port: 8081

spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        url: jdbc:mysql://db:3306/market
        password: "password"

    sql:
        init:
            schema-locations: classpath:db/init.sql
            # data-locations: classpath:db/data.sql
            mode: always
            
    data:
        redis:
            host: redis
            port: 6379
            database: 1

mail: 
    mail-address: "19550102041@163.com"
    password: "NWqddpAiPmttZrB9"
    redis-start-with: "mail-code:"